# Exported from Render on 2026-09-21T11:07:12Z
version: "1"
services:
- type: web
  name: upnex
  runtime: docker
  repo: https://github.com/Arjunsanthosh1777/UPNEX-Beyond-the-Static-Resume-Your-Career-s-Operating-System
  plan: free
  envVars:
  - key: COOKIE_SECURE
    sync: false
  - key: PORT
    sync: false
  - key: NODE_ENV
    sync: false
  region: oregon
  healthCheckPath: /api/health
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
